# .github/workflows/ptest.yml

name: Test-On-Push

on: push

jobs:
  Unit-Tests:
    name: Test code base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Build Deno Module
        run: deno run --allow-all --unstable index.js
      - name: Run Test Suite
        run: deno test --allow-none
