# .github/workflows/single-stage.yml

name: Single-Stage

on:
  push:
    branches: ['none']
jobs:
  Unit-Tests:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Use Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Run Test Suite
      run: deno test